### ISSUE TITLE
Is the example for `Prism` correct?

### ISSUE THREAD

**Issue by marick** [arturopala/elm-monocle#10]
Here's the example:

```elm
    string2IntPrism.getOption "17896" == Just 17896
    string2IntPrism.getOption "1a896" == Nothing
    string2IntPrism.reverseGet 1626767 = "1626767"
```

My reading of both the [Scala Monocle prism laws](https://julien-truffaut.github.io/Monocle/optics/prism.html) and the [Haskell prism laws](https://hackage.haskell.org/package/lens-4.15.4/docs/Control-Lens-Prism.html) suggest that doesn't work.

Here's the Scala description of the second law:

```scala
def partialRoundTripOneWay[S, A](p: Prism[S, A], a: A): Boolean =
  p.getOption(p.reverseGet(a)) == Some(a)
```

That suggests to me that `getOption (reverseGet "1626767") == Just 1626767`, but it will actually return `Nothing`. 

The Haskell doc defines the equivalent as its first law:

```haskell
First, if I `re` or `review` a value with a Prism and then `preview` or use (^?), I will get it back:

preview l (review l b) ≡ Just b
```

Your implementation is arguably more useful, since it seems the law restricts you to a sum type.

I'm probably confused.

**Comment by arturopala** [comment]
`Prism` applies where function from A to B is not total, this is why instead of `get` we have here `getOption`. Reverse function , in the direction from B to A, always exists.  Example shows conversion from String to Int which can only happen if all characters are digit and first one is not zero, on the other hand each Int have String representation.

**Comment by arturopala** [comment]
btw. your example should be:
`getOption (reverseGet 1626767) == Just 1626767`

**Comment by marick** [comment]
Are you saying that:
1. this implementation of `Prism` satisfies the same laws as the Scala and Haskell versions?
2. this implementation obeys different laws?

(Either is fine with me, but if it's (1), I'd like to understand why.)

**Comment by marick** [comment]
(By the way, thank you for the library. I've used it to good effect in a production Elm app.)

**Comment by arturopala** [comment]
My understanding is that this implementation of Prism satisfies the same laws as the Scala and [Haskell](https://hackage.haskell.org/package/lens-4.15.4/docs/Control-Lens-Prism.html)
1. `preview p (review p b) ≡ Just b` is `p.getOption (p. reverseGet b) == Just b`
2. If `preview p s ≡ Just a` then `review p a ≡ s` becomes:  If `p.getOption s == Just a` then `p.reverseGet a == s`

**Comment by ekmett** [comment]
The laws don't restrict you to a sum type. They restrict you to part of the target space.

Sums naturally fit this model, but so do other things.

If you inject into that space you get back what you put in.

Parsing is "morally" prism-like, but its unless every term in the language you parse has a unique-on-the-nose syntactic representation as a string you fail the law that says that if you successfully match with the prism to get Just a, and inject the result back in you get exactly 's'. 

For most parsers, this only holds up to considerations like whitespace, () placement, etc. Most don't round-trip exactly. We talk about "improper" optics when they only pass this equality on one side or the other (and its worth figuring out if its matching then injecting or injecting then matching that is on the nose, because compositions that agree on this ordering, also retain this property.)

**Comment by marick** [comment]
Can you explain that in terms of the laws, specifically:

```
def partialRoundTripOneWay[S, A](p: Prism[S, A], a: A): Boolean =
  p.getOption(p.reverseGet(a)) == Some(a)
```

**Comment by ekmett** [comment]
I confess I don't know the scala function names. I'm guessing getOption is `preview` / `(^?)`, and `reverseGet` is `review` or `(#)`?

if so then the law you gave is the same as

```haskell
(_Foo # a)^?_Foo = Just a
```

is one of 3 laws: Matching gets back what you inject.

The other two state that 

if you successfully match and put it back in you don't change anything.

```haskell
maybe s (_Foo #) $ s^?_Foo = s
```

These two laws are analogous to the first two lens laws

```haskell
get (set s a) = a
set s (get s a) = s
```

that you'll find over the bidirectional transformations literature.

Finally, matching twice with the same time is the same as matching once. Nothing changes the second time. We need a slightly better "match" than ^? to make that make sense:

```haskell
matching :: APrism s t a b -> s -> Either t a
```

limited to the two argument form you're using here you get:

```haskell
matching :: Prism' s a -> s -> Either s a
```

and then

either (matching _Foo) id (matching _Foo) = matching _Foo

is the analogue to the

```haskell
set (set s a) b = set s b
```

law for a "very well-behaved lens" in bidirectional transformation literature.

The connection between the lens laws and the prism laws draws out much more nicely and symmetrically using a commutative diagram, but its rather difficult to draw them here.

**Comment by marick** [comment]
I am a careless idiot. My apologies for wasting your time.

Somewhere, I'd seen an example of a prism that selected only a given string out of the infinite(ish) get of all possible strings. That is:

```
getOption("match") == Just "match"
getOption("anything else") == Nothing
```

... which doesn't follow the prism laws. (Right? Please, please be right.) I'd flagged that in my brain to think about later. And when I saw this example, I somehow didn't notice it was about the difference between valid and invalid strings -- I jumped to the conclusion it was about selecting one string. 

So then I went off applying laws to a different "prism" than the one you'd written. It was only when I actually tried to run the code in the repl that I saw my mistake. It stubbornly insisted on running the code I had, not the code I thought I had. Hmm... There might be a lesson there.

**Comment by arturopala** [comment]
No worries! It was a good exercise for me.

wt., 28 lis 2017 o 14:16 użytkownik Brian Marick <notifications@github.com>
napisał:

**Comment by ekmett** [comment]
What it should give back is Just () if it sees the string you are looking for rather than the exact string it matched, after all there is just one of them.
