### ISSUE TITLE
Infix operator alias for Lens.compose

### ISSUE THREAD

**Issue by Bastes** [arturopala/elm-monocle#11]
I really love monocle and the ability to use lenses to get and set values easily.

But since lenses are especially interesting when you can compose them, and since composition can be deep for deeply nested structures, it's a bit annoying and counter-intuitive to have to do this:
```elm
lens1 : Lens a b
lens2 : Lens b c
lens3 : Lens c d

lens13_1 : Lens a d
lens13_1 =
  lens3
    |> compose lens2
    |> compose lens1

-- OR

lens13_2 : Lens a d
lens13_2 =
  compose (compose lens1 lens2) lens3

-- OR

lens13_3 : Lens a d
lens13_3 =
  let
    lens12 = compose lens1 lens2
  in
    compose lens12 lens3

-- OR EVEN
lens13_4 : Lens a d
lens13_4 =
  compose lens1 <| compose lens2 lens3
```

All these patterns are grating to read. We usually solved it making "half-way" lenses like:
```elm
lens12 = compose lens1 lens2
lens13 = compose lens12 lens3
```

But I can't help thinking we might benefit from an infix Lens.compose alias allowing to do things like:
```elm
(<|>) = Lens.compose
lens13 = lens1 <|> lens2 <|> lens3
```

(I've actually done it in projects of my own that use lenses)

So, what do you think?

**Comment by arturopala** [comment]
looks as a good candidate por a PR, pls contribute

niedz., 3 gru 2017 o 13:05 użytkownik Michel Belleville <
notifications@github.com> napisał:

**Comment by Bastes** [comment]
Gladly ^^ I just didn't want to do it out of the blue without asking wether
it was a good idea first, and maybe discuss which symbol would be
appropriate for that operator.

Le dim. 3 déc. 2017 à 18:16, Artur Opala <notifications@github.com> a
écrit :

**Comment by Bastes** [comment]
Here, finally took time to implement it :smile:

**Comment by Bastes** [comment]
(sorry, it appears I have forgotten to bump the version up 😅 I'm fairly new to publishing packages in elm -completely new in fact- should I send you another pull request with the new version? I'm reading this can be done automatically using "elm-package bump", but I don't want to do something that'd mess with your repo)

**Comment by Bastes** [comment]
I just tried the `elm-package bump` and it seems to have done the job ; hence the new PR https://github.com/arturopala/elm-monocle/pull/13

**Comment by Bastes** [comment]
(and I guess we can close this now anyways ^^° sorry for not being very responsive the last few days)
