### ISSUE TITLE
Optional for list too

### ISSUE THREAD

**Issue by Bastes** [arturopala/elm-monocle#17]
This is more a question than an issue or request, but why is there an "array" to access an item at some place in an array and not the equivalent list? Is this an optimization thing or just an edge case that wasn't as urgent as others?

Since I feel it can be interesting to have, I'd be willing to add it to the codebase in a PR, unless there is a good reason for it not to exist :)

**Comment by arturopala** [comment]
I think it is just an `optimization`, feel free to contribute the stuff you would like to have in Common.

**Comment by Bastes** [comment]
Thanks, I'll get to it then ;) it's only a convenience method, really, but since it's more common to use lists than arrays in cases where traversing a few items is not a big issue, I guess it should be ok performance-wise with just a warning in the docs to use arrays when the list is big and/or changes are frequent and should be fast.

**Comment by Bastes** [comment]
Just one last thing: I bumped the version but I can't publish it since I'm not working on your repo ^^° would you mind publishing it?

Thanks a bunch :)

**Comment by arturopala** [comment]
Hi Michel, thank you for the code, the new version has been released.

**Comment by Bastes** [comment]
Thanks Arturo :)
