### ISSUE TITLE
Traversal

### ISSUE THREAD

**Issue by Bastes** [arturopala/elm-monocle#24]
Hi @arturopala :)

I've been toying with the idea of adding Traversal here for quite some time, and I've just bumped into a case where it'd be useful. So here's me asking whether you'd like a PR that'd add the a new Monocle.Traversal module (and composition functions in Compose) :) (I haven't started on it yet, and since I'm going to prepare this from my use case I'm open to your thoughts on what should be in it and how).

So, what do you say?

**Comment by arturopala** [comment]
Hi @Bastes, why not? I'm open to this idea.

**Comment by andys8** [comment]
Would be great. I'd be interested. Haven't found a package containing Traversal so far.

**Comment by Bastes** [comment]
Hey @andys8 :) sorry I haven't really found where to start with this so far, my use case has kinda disappeared since (changed companies, the new one has no Elm in it). I'd be interested if you had ideas on what you need from them actually, to define a scope.

**Comment by andys8** [comment]
Understandable. I haven't taken a look into other APIs so far. I'd be interested in sketching a PR as proposal when I find time and have an idea how it could look like.

**Comment by Bastes** [comment]
Sure :) I have had a hard time wrapping my head around them in haskell (to know the laws, etc.) and didn't find an obvious way to import the concept here (hence why I was stuck so far).

**Comment by Bastes** [comment]
Ok, so here's my intuition of what a traversal could be like in this context:
```
module Traversal exposing (Traversal, modify, list, array)

type alias Traversal collection item =
    (item -> item) -> collection -> collection

modify : Traversal collection item -> (item -> item) -> collection -> collection
list : Traversal (List a) a
array : Traversal (Array a) a


module Compose

isoWithTraversal : Traversal b c -> Iso a b -> Traversal a c
prismWithTraversal : Traversal b c -> Prism a b -> Traversal a c
lensWithTraversal : Traversal b c -> Lens a b -> Traversal a c
optionalWithTraversal : Traversal b c -> Optional a b -> Traversal a c
traversalWithIso : Iso b c -> Traversal a b -> Traversal a c
traversalWithPrism : Prism b c -> Traversal a b -> Traversal a c
traversalWithLens : Prism b c -> Traversal a b -> Traversal a c
traversalWithOptional : Prism b c -> Traversal a b -> Traversal a c
traversalWithTraversal : Traversal b c -> Traversal a b -> Traversal a c
```

What do you think?

**Comment by andys8** [comment]
I wrote a comment for 15 minutes on my phone that got lost 🥺

I'll just repeat it in short terms to dig into it later:

* The API constructor follows a different pattern than all other constructors (get/set) in `elm-monocle`
* Could this API (probably not meant to be complete) do more than `List/Array.map`?
* What is missing other than `modify`? What are the use cases in other languages?
* Will the approach work with other container's like nonempty list and zippers?
* Haskell's type implementation is `type Traversal s t a b = forall f. Applicative f => (a -> f b) -> s -> f t`. Ist it therefore more powerful and can provide more usages?


Those is the short form of the questions that came to my mind. Thanks a lot for your proposal. I want to have a deeper look and play around with it :)

**Comment by andys8** [comment]
This JavaScript library could be a good starting point for a minimal set of operations:

https://github.com/calmm-js/partial.lenses/blob/master/README.md#---traversals

**Comment by Bastes** [comment]
Thanks for your comments and suggestions @andys8 (and sorry for my late reply, my time disappeared in a vacations black hole ;p). I'll try to answer and explain why I suggested this very simple contract ASAP so we can keep the ball rolling :) also, thanks for the JS inspiration.

**Comment by Bastes** [comment]
- Haskell's type implementation is type Traversal s t a b = forall f. Applicative f => (a -> f b) -> s -> f t. Ist it therefore more powerful and can provide more usages?

This is on purpose ; it is indeed less powerful in the sense that it does not allow you to make some of the acrobatics full-fledged `Traversal s t a b` do, but so are `Lens s s a a` compared to `Lens s t a b` and `Prism s s a a` to `Prism s t a b`, and yet that's what elm-monocle give you because it's the most commonly useful. I was just following that design choice.

- The API constructor follows a different pattern than all other constructors (get/set) in elm-monocle

Yes ; the get/set pair works wonder when you have a 1-1 relationship between the origin and destination types, less so when there's a 1-n. Since the real value is in `modify` and composition for `Traversal` (and kind of for the other optics too), and considering we might as well keep things simple, I reduced the "contract" to its simplest expression: a `Traversal` is the operation of traversing (`map`) over the structure you use.

- Could this API (probably not meant to be complete) do more than List/Array.map?
- Will the approach work with other container's like nonempty list and zippers?

This is kind of the same question (or at least I think it's better answering both at the same time).
Since this definition of `Traversal` is an alias to `(a -> a) -> s -> s` anything that implements a `map : (a -> b) -> F a -> F b` is eligible ; all you have to do is use the `map` function as `Traversal` and you're good to go. That should be pointed out in the README too I think.

- What is missing other than modify? What are the use cases in other languages?

That's why I was interested in insight from someone else that might point out concepts I might have missed, but it looks like we haven't seen what so far which I think is a good sign ;) I'll probably give it a try tonight at home to prepare a rough PR so we can start discussing with real code.

**Comment by Gauteab** [comment]
@Bastes how is it going? :) Did you run into a wall or did you simply not have the time?

**Comment by Bastes** [comment]
@Gauteab sorry, I've somehow missed github's notification :sweat_smile:

So, long story short, I changed jobs and since I wasn't making Elm as much as I used to and was busy with something else (and was kinda not quite sure where most of the values for traversal in Elm was) I was taking time to reflect (aka slacking and having white page anxiety).

But since I also took some time to learn a bit more about traversals in Haskell, I'm having a go at implementing what I had in mind, with a little bit more (a `some` method that allows for a traversal that only applies changes on some of the values depending on a condition).

There are use cases I thought about and couldn't / wouldn't implement (like a traversal that provides indexes of traversed elements as well as the elements themselves, or a function to collect traversed elements in a list) but that's a first draft and maybe I (or someone else) will see what is missing and how to implement it.

I'll link to the PR when it's good and ready :slightly_smiling_face:

**Comment by arturopala** [comment]
@andys8 @Gauteab @krisajenkins Hi guys, how do you like the proposal? I'm inclined to merge it, any comments?

**Comment by arturopala** [comment]
version 2.2.0 with Traversal has been released, thanks to @Bastes 🎉

**Comment by Bastes** [comment]
Thank you @arturopala :) I've already got an idea on how to test this ;)
