### ISSUE TITLE
Example in README doesn't work, no operator "=>"

### ISSUE THREAD

**Issue by malaire** [arturopala/elm-monocle#25]
The following example in README doesn't work. I also tried changing `=>` to `>>` in case it was just a typo, but it still doesn't compile, just gives a lof of type errors.

    regionOfPlace : Optional Place String
    regionOfPlace =
        addressOfPlace => regionOfAddress

**Comment by arturopala** [comment]
Thanks, @malaire, I will take a look at this.

**Comment by andys8** [comment]
Has to be replaced with `Optional.compose` or `Compose.optionalWithOptional`

**Comment by Bastes** [comment]
PR ready :)
