### ISSUE TITLE
Merge Prism and Optional

### ISSUE THREAD

**Issue by nikita-volkov** [arturopala/elm-monocle#26]
I'm failing to see the benefit from isolation of those two abstractions. Both serve the same purpose and Prisms end up being Optional, once composed any way. Also there's no such concept as Optional in the classical lens libraries in Haskell, so it's a source of confusion for people with such background (I know it was for me).

So I suggest not to breed concepts unless you have a good reason and remove the current implementation of `Prism` and rename `Optional` to `Prism`.

**Comment by andys8** [comment]
Interesting. I didn't know it doesn't exist in Haskell. It does in [Scala](https://julien-truffaut.github.io/Monocle/optics/optional.html).

For me, not coming from Haskell, it looks like they serve a different purpose and have different type signatures. `Prism` converts structures, `Optional` sets nested values.

https://mobile.twitter.com/puffnfresh/status/654862731548446720

https://stackoverflow.com/questions/33725534/are-monocles-optionals-the-same-as-partial-lenses

I'm not arguing for one or the other. Instead I'm curious how it's done in Haskell and what the advantages of removing `Optional` are.

**Comment by arturopala** [comment]
I'm happy and welcome to accept PRs but would like to keep things backward
compatible when reasonable, i.e. not forced by the ELM changes.

czw., 25 lip 2019, 01:17 użytkownik Andy <notifications@github.com> napisał:

**Comment by nikita-volkov** [comment]
> For me, not coming from Haskell, it looks like they serve a different purpose and have different type signatures. Prism converts structures, Optional sets nested values.

Actually, I've screwed up and you've helped me realise it. Thanks!

`Prism` does the same thing in Haskell as both in this library and Scala. Haskell does in fact lack `Optional`: see [the abstractions hierarchy](http://i.imgur.com/ALlbPRa.png) (from [the "lens" library](https://hackage.haskell.org/package/lens)). It however does have a thing that achieves the same purpose as `Optional`, only in a more general way: it's `Traversal` and the difference is that it lets you point at multiple locations.

This made me google for traversals in Scala's Monocle, and I've discovered that the library has both `Traversal` and `Optional`: https://julien-truffaut.github.io/Monocle/optics/traversal.html. So while I still am not sold on the usefulness of `Optional`, since we don't have `Traversal` here yet, it's better that we have that at least. I'll close the issue.

**Comment by andys8** [comment]
Thanks @nikita-volkov, I learned something.

I am wondering how traversals (#24) should be implemented and if they're useful for something else than `List`. They could work for `Array`, `Maybe` and other container's though. I would like to play around with them. The API will probably look like those in other languages without type classes.
