### ISSUE TITLE
Implementation specifics question

### ISSUE THREAD

**Issue by gyzerok** [arturopala/elm-monocle#9]
Hi @arturopala  thanks you for such a nice library!

Can you, please, tell me why you chose to use records with functions as properties instead of using opaque type and functions like `Monocle.get`, `Monocle.set`, like for example, in [Focus](http://package.elm-lang.org/packages/evancz/focus/2.0.2/Focus) library?
I am trying to understand if it was just a style preference or there was more to it :)

**Comment by arturopala** [comment]
Hi @gyzerok, the main reason was my preference for simple and obvious solutions. It was also my first attempt to write it in Elm, so maybe not the best one, if you have arguments to do it differently I'm keen to here from you.

**Comment by gyzerok** [comment]
Thanks for the response! I don't have any specific arguments, just wanted to know your reasoning.
